UPSTREAM: wifi: rtw89: use flexible array member in rtw89_btc_btf_tlv
struct rtw89_btc_btf_tlv contains a one-byte member that is intended as a
flexible array:

In function 'fortify_memcpy_chk',
    inlined from '_append_tdma' at drivers/net/wireless/realtek/rtw89/coex.c:1579:3:
include/linux/fortify-string.h:583:25: error: call to '__write_overflow_field' declared with attribute warning: detected write beyond size of field (1st parameter); maybe use struct_group()? [-Werror=attribute-warning]
  583 |                         __write_overflow_field(p_size_field, size);
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Make this actually use a flexible array to let the compiler understand.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Reviewed-by: Ping-Ke Shih <pkshih@realtek.com>
Reviewed-by: Gustavo A. R. Silva <gustavoars@kernel.org>
Signed-off-by: Kalle Valo <kvalo@kernel.org>
Link: https://lore.kernel.org/r/20230523113241.2772811-1-arnd@kernel.org
(cherry picked from commit 47e612268ea02f7d2bcbaa47528698b5be61a8cf)

BUG=b:351289055
TEST=verify suite:wifi_matfunc and suite:wifi_perf on dedede with 8852B.

Cq-Depend: chromium:5853381
Change-Id: Ie7cb8b9046b03e15143bed6112d5d7f45c3d3336
Signed-off-by: Zong-Zhe Yang <kevin_yang@realtek.com>
Signed-off-by: Andrzej Ostruszka <andrzejo@google.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/5850553
Commit-Queue: David Ruth <druth@chromium.org>
Reviewed-by: David Ruth <druth@chromium.org>
Reviewed-by: Sean Paul <sean@poorly.run>