UPSTREAM: wifi: rtw89: fix rtw89_read_chip_ver() for RTL8852B and RTL8851B
The if statement is reversed so it will not record the chip version.
This was detected using Smatch:

    drivers/net/wireless/realtek/rtw89/core.c:3593 rtw89_read_chip_ver()
    error: uninitialized symbol 'val'.

Fixes: a6fb2bb84654 ("wifi: rtw89: read version of analog hardware")
Signed-off-by: Dan Carpenter <dan.carpenter@linaro.org>
Acked-by: Ping-Ke Shih <pkshih@realtek.com>
Signed-off-by: Kalle Valo <kvalo@kernel.org>
Link: https://lore.kernel.org/r/e4d912a2-37f8-4068-8861-7b9494ae731b@kili.mountain
(cherry picked from commit 9d4f491b860ea6d04471c3342093b86a46eee63e)

BUG=b:351289055
TEST=verify suite:wifi_matfunc and suite:wifi_perf on dedede with
     8852A/8852B.

Change-Id: I40ba1a42d0deeb33d35eba2ef6dd6bfb62f583f4
Signed-off-by: Zong-Zhe Yang <kevin_yang@realtek.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/5701326
Reviewed-by: David Ruth <druth@chromium.org>
Tested-by: David Ruth <druth@chromium.org>
Reviewed-by: Sean Paul <sean@poorly.run>
Commit-Queue: David Ruth <druth@chromium.org>